CREATE TABLE `data_mapping_rek_a` (
  `id` int(11) NOT NULL auto_increment,
  `kode_rekening_spbmd` varchar(20) NOT NULL,
  `uraian_rekening_spbmd` text DEFAULT NULL,
  `kode_rekening_ebmd` varchar(20) DEFAULT NULL,
  `uraian_rekening_ebmd` text DEFAULT NULL,
  `update_at` datetime NOT NULL,
  `active` tinyint(4) DEFAULT 1,
  PRIMARY KEY  (id)
);
CREATE TABLE `data_laporoan_kib_a` (
  `id` int(11) NOT NULL auto_increment,
  `skpd` varchar(255) DEFAULT NULL,
  `kode_skpd` varchar(255) DEFAULT NULL,
  `nama_lokasi` text DEFAULT NULL,
  `kode_lokasi` varchar(255) DEFAULT NULL,
  `kode_aset` varchar(255) DEFAULT NULL,
  `nama_aset` text DEFAULT NULL,
  `tanggal_perolehan` date DEFAULT NULL,
  `tanggal_pengadaan` date DEFAULT NULL,
  `kondisi` text DEFAULT NULL,
  `no_register` int(50) DEFAULT NULL,
  `asal_usul` text DEFAULT NULL,
  `luas_tanah` varchar(255) DEFAULT NULL,
  `alamat` text DEFAULT NULL,
  `keterangan` text DEFAULT NULL,
  `satuan` varchar(50) DEFAULT NULL,
  `klasifikasi` text DEFAULT NULL,
  `tanggal_sertifikat` date DEFAULT NULL,
  `no_sertifikat` varchar(50) DEFAULT NULL,
  `status_sertifikat` text DEFAULT NULL,
  `umur_ekonomis` int(50) DEFAULT NULL,
  `masa_pakai` varchar(255) DEFAULT NULL,
  `nilai_perolehan` int(50) DEFAULT NULL,
  `jumlah_barang` int(50) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp,
  `active` tinyint(4) DEFAULT 1,
 PRIMARY KEY(id)
);